### ISSUE TITLE
General question about use

### ISSUE THREAD

**Issue by jusso-dev** [microsoft/electionguard-dotnet#60]
Just a general question, is there a getting start guide for this? also, I notice that this really only provides the cryptography layer and persists election results to disk. Is the intent of this for developers to consume this SDK for the cryptography benefits and it's BYO in regards to REST API and storage requirements?

**Comment by AddressXception** [comment]
Hi, sorry for the delayed response.  The [TestApp](https://github.com/microsoft/electionguard-dotnet/blob/master/tests/TestApp/Program.cs) shows how this library can be consumed using the file system specifically.

There is an example REST API example here:

https://github.com/microsoft/electionguard-web-api

Because of the way the core encryption library currently works, the Rest API also expects to store artifacts on the filesystem, but it also returns necessary data results via HTTP for each call.

Specifically, check out the `.postman` directory for example usage.  

HTH

**Comment by keithrfung** [comment]
Closing issue because inquiry was answered.
